### ISSUE TITLE
is-disabled Deprecated

### ISSUE THREAD

**Issue by Tibincrunch** [JDilleen/datatables-bulma#1]
The "is-disabled" CSS class has been deprecated in favor of the disabled HTML attribute per the Bulma docs. [More info](https://github.com/jgthms/bulma/issues/276). Using dataTables.bulma.js allows the user to click on the ellipsis when available and there's nowhere for them to go, resulting in [this error](https://datatables.net/manual/tech-notes/5).

![ellipsis_error](https://cloud.githubusercontent.com/assets/11925098/26253912/e49a0132-3c82-11e7-97a2-005398d201f4.png)

I believe the fix is to remove any appended "is-disabled" classes and add the disabled property where appropriate. My JS skills are severely lacking so I wasn't able to figure out how to do this myself.

**Comment by JDilleen** [comment]
@Tibincrunch - I've fixed this, both Previous, Next and ellipsis buttons will now display as disabled via the attribute. Sorry for the delay!

**Comment by kresli** [comment]
I just hit on the issue using typescript and react. Because `disabled` is not valid attribute for anchor, my typescript is complaining all the time. There is no way around this but to create the style by my self. 
Please consider to bring the class `is-disabled` back to life at least. 
Thank you.

**Comment by itised** [comment]
I think using an invalid attribute instead of a regular class is enough of a reason to bring back the `is-disabled` class, but there are valid reasons to bring back that `is-disabled` class even for elements where `disabled` is a valid attribute. 

For example, I'd like to style a button as disabled until a certain condition is met. However, when the user clicks on the disabled button, I would like to let them know exactly why it has been disabled. Right now I can't do that, because the only way to style the button as disabled it to use the `disabled` attribute, which means I can't respond to click events.

I think keeping the `is-disabled` class but not disabling pointer events would be the best solution. Let the programmer handle the functionality, and let Bulma handle the styling. 

For elements that actually have `disabled` attributes, I think it would be redundant to also require the `is-disabled` class. The same disabled styles can be applied to elements with the `is-disabled` class or the `disabled` attribute, but the programmer can decide which to use based on the functionality they want.
