### ISSUE TITLE
Sorting Icons

### ISSUE THREAD

**Issue by Tibincrunch** [JDilleen/datatables-bulma#2]
When using dataTables.bulma.css there are two sets of sorting icons shown in the table header, one from Font Awesome and the other I'm guessing from DataTables. If I comment out lines 51, 55, and 59 the issue goes away.

![sorting_icons](https://cloud.githubusercontent.com/assets/11925098/26254636/3c397984-3c85-11e7-9b89-bb51d4400078.png)

**Comment by JDilleen** [comment]
@Tibincrunch - This is caused by the inclusion of the jquery.datatables.css file as well as my datatables.bulma.css file. The original CSS is inserting the default (sort_asc, sort_desc and sort_both) icons. There's no need to include both files, you can remove the jquery.datatables.css file in favour of my file.
